### ISSUE TITLE
Release 2.0.0?

### ISSUE THREAD

**Issue by layertwo** [mentalisttraceur/python-macaddress#16]
I'm noticing that there's an older version on PyPi (1.2.0), but the latest here is 2.0.0. Is there any plan to release that to PyPi (I didn't compare the differences between what's in 1.2.0 and 2.0.0).

Thanks!

**Comment by mentalisttraceur** [comment]
2.0.0 is unfinished, but hopefully soon!

There's at least one change in the current GitHub which is technically a breaking API change (only very minor edge cases would break, but I take API compatibility very seriously), hence the version bump in the source, but it's not ready yet.

I want to finish some of the design thoughts I'm still having about some of the other stuff (see open issues) before I start rolling new releases.

**Comment by mentalisttraceur** [comment]
Ehh, well, #4 is also a hangup, in that if I decide to go with making `HWAddress` a metaclass or ABC, then maybe that's worth including in 2.0.0 as well.

**Comment by layertwo** [comment]
If not impossible, would love to see Git tags used for easy identification of what changes have been made between each version.

**Comment by mentalisttraceur** [comment]
Cheers. I'll probably start doing tags eventually (sooner now that a user has asked).

**Comment by mentalisttraceur** [comment]
Sorry for delays. Had COVID and some life stuff. Planning to give this library a some of my time and push to 2.0.0 this week.

**Comment by mentalisttraceur** [comment]
@layertwo tags for each release added, finally

**Comment by mentalisttraceur** [comment]
Okay, 2.0.0 is finally moving forward, because I've decided I will *not* be including prefix cast construction ( #8 ) (and thus also not including removal of `.oui` ( #13 )). The prefix cast construction was holding this up a lot, because I was feeling compelled to rethink that behavior.

So that reduces the breaking changes down to minor ones, each of which should affect approximately nobody:

* `macaddress.MAC` becomes an alias instead of subclass of `macaddress.EUI48` ( #9 ) ( 00ce0d34459544c7d800f282aca4434406873c17 ).
* Get size from class instead of instance ( #6 ) ( d66da7fe3d2980e1cdf3c121b10cd5c97539fbca ).
* Get formats from class instead of instance ( #14 ) ( 896a58fbcae5f649c05106e9cb1d978ae6f4912b ).
* Equality, hashing, and copy construction now uses address size ~~instead of type~~ for compatibility ( #3 ) ( 1562c519c2140e126c62e4cb3af5b8d2f59faba1 ).
* [maybe] Add `__init_subclass__` hook that at least rejects wrongly sized `formats` entries ( #4 ).

But now the only holdup is that I'm finding myself thinking of tweaking the "instead of type" part of the equality(/hashing)/casting change.

**Comment by mentalisttraceur** [comment]
Done.
